### ISSUE TITLE
API Control of Air Conditioner Not Functioning Properly Since 11/8 (JST)

### ISSUE THREAD

**Issue by yyverse** [OpenWonderLabs/SwitchBotAPI#363]
### Current Situation

Since last week, starting on November 8th at 5:00 PM JST, I've been unable to control my air conditioner via the API using infrared commands. However, controlling the air conditioner from the SwitchBot app works fine. I kindly request you to investigate this issue.

### Logs

```markdown
My script attempts to operate the air conditioner every 5 minutes, and it has been functioning normally for over a year without any issues like this. I can determine whether the operations are successful by checking the history in the SwitchBot app.
```

### Configuration

```json
The following command is being used:


parameter = "2,1,1,on"
commands = dict(
    command = 'setAll',
    parameter = parameter,
    commandType = 'command',
)
set_commands(deviceId, commands)
```
```


### Environment

- OS: Debian GNU/Linux 11 (bullseye)
- Software: Python3.9
- Node: PC
- npm:


### Additional Context

Please assist in identifying and resolving the issue affecting API-based operations.

**Comment by tcavin** [comment]
Hi,
I can also confirm there is something wrong with the API when sending command to my Air Conditioner 
I didn't change any line of my code
Whatever command we request to the API (see below for mine), It seems to forward a default command (25,cold, ...)
My command : 
```
{
    "command": "setAll",
    "parameter": "22,5,1,off",
    "commandType": "command"
}
```
I checked this behavior with v1.0 of the API, but also with v1.1

**Comment by Michel-Bos-HA** [comment]
Hi there, I encountered this issue since this morning, 16th November, starting around 10.45 AM.

Any command from within Homey resukts in "Cold, 25".

**Comment by davidsak** [comment]
Just chiming in to say I’m having the same issue sending commands to my AC. If I send the “turnOn” or “turnOff” command it works fine but “sandaAll” no longer works. Everything was working fine before and nothing was modified in my code.

**Comment by tcavin** [comment]
> Hi, I can also confirm there is something wrong with the API when sending command to my Air Conditioner I didn't change any line of my code Whatever command requested to the API (see below for mine), It always seems to transmit a default command (25, cold, ...)
> 
> My command :
> 
> ```
> {
>     "command": "setAll",
>     "parameter": "22,5,1,off",
>     "commandType": "command"
> }
> ```
> 
> I checked this behavior with v1.0 of the API, but also with v1.1 Thanks for your help solving this issue

@yyverse could you change the label from question to bug ?

@SwitchBot-Wonderlabs could you investigate because this bug blocks our installations, thx 🙏

**Comment by Michel-Bos-HA** [comment]
It looks like the openapi issue is solved. My commands seem to work. Fingers crossed off course :-)

**Comment by SeraphicRav** [comment]
> It looks like the openapi issue is solved. My commands seem to work. Fingers crossed off course :-)

Some users reported the issue in Home Assistant but it worked for me. I guess some servers are faulty, others not...

**Comment by zibbs** [comment]
Still doesn't work for me... In the switchbot app works fine, but not though the api or integration in HA.

**Comment by davidsak** [comment]
setAll with a decimal in the temperature parameter does not seem to work anymore but if called with an integer it does. So for instance, “20.3,5,2,on” does not work but “20,5,2,on” does.

**Comment by irfane29** [comment]
I have an issue with controlling A/C temperature through home assistant, it was working until now. But with the switchbot app, all commands are working fine. 
Please check on your server side what the issue, thanks

**Comment by rpaillot** [comment]
HVAC command started working again 2 or 3 days ago, but "temperature" doesn't work in HA.

"“Failed to call service climate/set_temperature. Unknown error”" (translated from FR)

**Comment by MrXANA91** [comment]
> setAll with a decimal in the temperature parameter does not seem to work anymore but if called with an integer it does. So for instance, “20.3,5,2,on” does not work but “20,5,2,on” does.

Can confirm

**Comment by zibbs** [comment]
> > setAll with a decimal in the temperature parameter does not seem to work anymore but if called with an integer it does. So for instance, “20.3,5,2,on” does not work but “20,5,2,on” does.
> 
> Can confirm

I never used decimals and still doesn't work for me. Seems like nothing is called. The HUB doesn't blink when the command is send.

**Comment by rpaillot** [comment]
I just got an email answer from switchbot saying they fixed the issue.
Indeed we can now turnoff and turnon the ACs and set heat or cold and it works.

But we need to be able to set the temperature and I sent them a bunch of screen capture of what's happening. Hoping they will fix that too in a few days.

**Comment by darkaeden** [comment]
Turn ON/OFF/HEat/Cold works yet setting a different temperature than default triggers climate/set_temperature failure.

**Comment by rpaillot** [comment]
> Turn ON/OFF/HEat/Cold works yet setting a different temperature than default triggers climate/set_temperature failure.

Absolutely. same issue. Still ongoing

**Comment by rpaillot** [comment]
Ok   I have some news
I think something in the API may have changed or something was broken in the Switchbot Cloud Integration, either way.
Switchbot support advised me to read the API documentation again, then in 
Terminal I used this command 

curl -X POST "https://api.switch-bot.com/v1.0/devices/-YOUR-DEVICE-ID-HERE/commands" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer YOUR API KEY HERE" \
-d '{
  "command": "setAll",
  "parameter": "22,5,1,on",
  "commandType": "command"
}'

And this seems to work perfectly and seems to change the temperature also. 

Here's the section of the API 

![Screenshot 2024-12-02 at 10 12 34](https://github.com/user-attachments/assets/e45d471e-e2b1-45f6-9ad5-bdddf080672b)


I dont know how to use GitHub efficiently, how can we contact here the developer of the switchbot cloud integration to fix the issue ? 

I could make automations to send curl commands, but not very friendly ;)

**Comment by SeraphicRav** [comment]
It is OK, I am following the conversation, I made a bugfix pull request
